### PR TITLE
Fix the user cycle getting

### PR DESCRIPTION
**Pull request by ch1ck3n-byte**
it used to had an error

### CODE REVIEW

**Comment by darkdarcool** [comment]
It seems to give an error when I run https://repldata.ch1ck3n.repl.co/cycles/darkdarcool

**Comment by ch1ck3n-byte** [comment]
hmm il look into it

**Comment by ch1ck3n-byte** [comment]
It should work now https://repldata.ch1ck3n.repl.co/cycles/darkdarcool

**Comment by darkdarcool** [comment]
k cool now it works

**Pull request merged**
