### PR TITLE
Made version num easier to access

### PR DESCRIPTION
**Pull request by Tiger-The-Cat**
Nothing complicated, just moved the version variable to the top.

### CODE REVIEW

**Review by darkdarcool — CHANGES_REQUESTED** [review]
Please add a class to them called info

**Comment by darkdarcool** [comment]
I put the class at the top myself, thanks for the suggestion!

**Comment by Tiger-The-Cat** [comment]
> 
> 
> Please add a class to them called info

Do you want me to put the version variable in info class?

**Comment by darkdarcool** [comment]
i did it myself, look at the code

**Pull request closed without merging**
